repos:
  # Ruff linter + formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # Black code formatter
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  # Pyright type checking (only on src/ directory)
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
        files: ^src/

  # TypeScript type checking for web directory
  - repo: local
    hooks:
      - id: typecheck-web
        name: TypeScript typecheck (web)
        entry: bash -c 'cd web && npm run typecheck'
        language: system
        files: ^web/.*\.(ts|tsx)$
        pass_filenames: false

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
