version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - ENV=local
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/app/logs
      - ./tmp:/tmp/dwell # [TODO] clean this app. Switch to post

volumes:
  redis_data:
