version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dwell
      POSTGRES_USER: dwell_user
      POSTGRES_PASSWORD: dwell_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  worker:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      - ENV=local
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
  postgres_data:
